### ISSUE TITLE
Display correct open en close time in Bite order screen

### ISSUE THREAD

**Issue by mschilling** [mschilling/bite-android#1]
The Bite order screen should display the real times (use `order.open_time` and `order.close_time`). Please remove the static times ;-)

![screenshot_20170126-122541](https://cloud.githubusercontent.com/assets/7045335/22329672/a6e73594-e3c2-11e6-9c5b-4ca7e4cb09da.png)

**Comment by cassshh** [comment]
Time format should be 24hours.
(`HH:mm`)
